branch-defaults:
  master:
    environment: parsedashboard-1
global:
  application_name: ParseDashboard
  default_ec2_keyname: null
  default_platform: Docker 1.9.1
  default_region: us-west-1
  profile: eb-cli
  sc: git
